name: deploy-sa
on:
  workflow_dispatch:
  
env:
  AZ_RG_Name: RG2
  RG_LOC: WestEurope
 
 
permissions:
  id-token: write
  contents: read
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sign in to Azure
        uses: azure/login@v1
        with:
          client-id: 
          tenant-id: 
          subscription-id: 

      - name: deploy RG
        uses: azure/cli@v1
        with:
         inlineScript:
          az group create --name ${{env.AZ_RG_Name}}  --location ${{env.RG_LOC}}
          
      - name: deploy storage
        uses: azure/arm-deploy@v1
        with:
         deploymentName: ${{github.run_Number}}
         resourceGroupName: ${{env.AZ_RG_Name}}
         template: ./sa.bicep
